### ISSUE TITLE
gh-pages branch?

### ISSUE THREAD

**Issue by jpdevries** [accdc/csun-2017#1]
This content is incredibly useful! Just had a thought, would be great if there were a gh-pages branch so it were hosted at accdc.github.io/csun-2017

**Comment by accdc** [comment]
Thanks, I hadn't thought of that. Will definitely look into it!

**Comment by accdc** [comment]
Hi,
Thanks again for the suggestion, I moved all of the executable folders into a docs folder and it now runs as the live pages as well.

1 Static Roles: https://accdc.github.io/csun-2017/1%20Static%20Roles.htm

2 Pseudo Interactive Roles: https://accdc.github.io/csun-2017/2%20Pseudo%20Interactive%20Roles.htm

3 Simple and Complex Interactive Roles: https://accdc.github.io/csun-2017/3%20Simple%20and%20Complex%20Interactive%20Roles.htm

These links have been added to the project home page as well.
